repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort
        args: [
          '--profile', 'black',
          '--filter-files',
          '-l 120',
        ]
  - repo: https:///github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        exclude: ^.*\b(migrations)\b.*$
        args: [
          '-l 120',
        ]