services:
  postgres:
    container_name: postgres_tables
    hostname: postgres
    image: postgres:15
    environment:
       - POSTGRES_USER=${DJANGO_DATABASE_USER}
       - POSTGRES_PASSWORD=${DJANGO_DATABASE_PASSWORD}
       - POSTGRES_DB=${DJANGO_DATABASE_NAME}
    restart: on-failure
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  backend-tables:
    build: ./dynamic_tables
    command: >
      sh -c "python manage.py runserver
      0.0.0.0:${DOCKER_BACKEND_PORT}"
    container_name: backend_tables
    depends_on:
      - postgres
    ports:
      - "${DOCKER_EGRESS_IP}:${DOCKER_BACKEND_PORT}:${DOCKER_BACKEND_PORT}"
    hostname: backend
    volumes:
      - ./dynamic_tables:/app
    restart: on-failure
    env_file:
      - .env

volumes:
  postgresql_data: