# Generated by Django 5.0.6 on 2024-05-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicmodelfield',
            name='allow_blank',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dynamicmodelfield',
            name='allow_null',
            field=models.BooleanField(default=True),
        ),
    ]
