# Generated by Django 5.0.6 on 2024-05-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0002_alter_dynamicmodelfield_allow_blank_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dynamicmodelfield",
            name="name",
            field=models.CharField(max_length=32),
        ),
        migrations.AddConstraint(
            model_name="dynamicmodelfield",
            constraint=models.UniqueConstraint(
                fields=("dynamic_model", "name"), name="unique_dynamic_model_name"
            ),
        ),
    ]
