# Generated by Django 5.0.6 on 2024-05-24 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0003_alter_dynamicmodelfield_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dynamicmodelfield",
            name="allow_blank",
        ),
        migrations.AlterField(
            model_name="dynamicmodel",
            name="name",
            field=models.CharField(
                max_length=32,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only letters are allowed.", regex="^[a-zA-Z]+$"
                    )
                ],
            ),
        ),
    ]
